### PR TITLE
Added formatISO8601

### PR DESCRIPTION
**Pull request by seanhess**
I needed a way to pass timestamps back and forth between client and server and had to look up ISO-8601. Thought it might be useful for others. Please let me know if you'd like me to change or clean anything up!

### CODE REVIEW

**Comment by mgold** [comment]
I'm glad the library is useful to you! I'm not sure this is worth exporting as a separate function, but I can add it to the docs. Does that make sense?

**Comment by seanhess** [comment]
Sure, it could work. 

Note, however, that core's Date.fromString does parse this format, and that there's currently no function in any library that serializes a Date in any standard way. I've used this format on every project for the last N years. It's quite common. Still think it's not worth it? Functions are pretty cheap :) You could add more common formats as functions too? 

Or even better: why don't we export a few common format strings, like ISO-8601 and others, but as strings. Then you can compose with `Date.Format.format` like this:

    Date.format Date.iso8601 myDate

It's basically as cheap as documentation but gives it a place to live.

**Comment by mgold** [comment]
Eh, sure, why not?

**Comment by seanhess** [comment]
Do you like my second idea better? I was just making the change.

**Comment by mgold** [comment]
Nah, I'll add the function. I just want the library to be helpful, so I'm taking your suggestion.

**Comment by seanhess** [comment]
Ok thanks Max!

**Pull request merged**
