### PR TITLE
Upgrade to 0.18

### PR DESCRIPTION
**Pull request by julianjelfs**
Had to change the way the tests are run a little bit. Also the tests are not resilient to timezone changes but I think this is a pre-existing problem. I will try to improve that but I don't know how to create UTC dates in elm at the moment.

### CODE REVIEW

**Comment by stil4m** [comment]
Maybe it is better to make an issue for the timezone resilient tests? This would allow users to already use this library in`0.18` :)

**Comment by julianjelfs** [comment]
Yes I'm working on fixing the tests now

**Comment by mgold** [comment]
Looks great, thanks!

**Comment by mgold** [comment]
BTW, if you're not seeing test output, try `npm install -g elm-test` again.

**Comment by mgold** [comment]
1.1.7 published!

**Pull request merged**
